# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Build Validation

on:
  pull_request:
    branches: [ "alpha" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out flightscreen
      uses: actions/checkout@v4
    - name: Check out matrix library
      uses: actions/checkout@v4
      with:
        repository: 'hzeller/rpi-rgb-led-matrix'
        path: 'rpi-rgb-led-matrix'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install python3-dev cython3 -y
    - name: build-python
      run: make -C rpi-rgb-led-matrix build-python
    - name: install-python
      run: sudo make -C rpi-rgb-led-matrix install-python
    - name: Test with pytest
      run: |
        pytest
